name: HTML

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        path: main
    - name: Build HTML for main
      run: | 
           wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.17/java-11-widoco-1.4.17-jar-with-dependencies.jar
           mkdir public 
           java -jar widoco.jar -ontFile main/pmd_core.ttl -outFolder public -htaccess -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
           cp public/index-en.html public/index.html
    - uses: actions/checkout@v3
      with:
        ref: v2.0.7
        path: v2.0.7
    - name: Build HTML for 2.0.7
      run: | 
           mkdir public/2.0.7 
           java -jar widoco.jar -ontFile v2.0.7/pmd_core.ttl -outFolder public/2.0.7  -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl           
           ls public/2.0.7/           
           cp public/2.0.7/index-en.html public/2.0.7/index.html

    - uses: actions/checkout@v3
      with:
        ref: v2.0.8
        path: v2.0.8
    - name: Build HTML for 2.0.8
      run: | 
           mkdir public/2.0.8 
           java -jar widoco.jar -ontFile v2.0.8/pmd_core.ttl -outFolder public/2.0.8  -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl           
           ls public/2.0.8/           
           cp public/2.0.8/index-en.html public/2.0.8/index.html

    - uses: actions/checkout@v3
      with:
        ref: develop-3.0.0
        path: v3.0.0
    - name: Build HTML for 3.0.0
      run: | 

           cd v3.0.0
           curl -L -o robot.jar "https://github.com/ontodev/robot/releases/download/v1.9.5/robot.jar"
           
           # merge all modules to one file
           # (but, do not merge the external imports, e.g. iao, etc)
           
           java -jar robot.jar merge --catalog catalog-v001.xml --collapse-import-closure false --input pmd-core.ttl --inputs "modules/*.ttl" --output merged.ttl 

           # remove the module import statements 
           java -jar robot.jar merge --catalog catalog-v001.xml --collapse-import-closure false --input merged.ttl --inputs "modules/*.ttl" convert --output merged.ofn
           grep -v "Import(<" merged.ofn > merged2.ofn

           # convert to turtle again, and add imports of external ontolgies
           java -jar robot.jar convert --input merged2.ofn --output merged3.ttl
           echo "<https://w3id.org/pmd/co> owl:imports <http://purl.obolibrary.org/obo/bfo/2020/bfo.owl> ," >> merged3.ttl
           echo "<http://purl.obolibrary.org/obo/iao/2022-11-07/iao.owl> , " >> merged3.ttl
           echo "<http://purl.obolibrary.org/obo/ro/releases/2023-08-18/core.owl> ." >> merged3.ttl

           # just another convert to make it beautiful
           java -jar robot.jar convert --input merged3.ttl --output merged4.ttl

           cd ..
           mkdir public/3.0.0
           java -jar widoco.jar -ontFile v3.0.0/merged4.ttl -outFolder public/3.0.0  -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl           
           ls public/3.0.0/           
           cp public/3.0.0/index-en.html public/3.0.0/index.html

           
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
