name: quality checks 
on:
  push:
    branches:
    - develop-3.0.0
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: develop-3.0.0
        path: main
    - name: quality checks  
      run: |
           curl -L -o robot.jar "https://github.com/ontodev/robot/releases/latest/download/robot.jar"
           java -jar robot.jar --version

           java -jar robot.jar reason --reasoner elk --input main/pmd-core.ttl --output main/pmd-core-reasoned.ttl

           java -jar robot.jar validate-profile --profile DL --input main/pmd-core-reasoned.ttl --output validation.txt
           cat validation.txt
           java -jar robot.jar verify --input main/pmd-core-reasoned.ttl --queries main/.github/workflow_resources/qc-queries/label-missing.sparql  
           #java -jar robot.jar verify --input main/pmd-core-reasoned.ttl --queries main/.github/workflow_resources/qc-queries/isdefinedby-missing.sparql  
           java -jar robot.jar verify --input main/pmd-core-reasoned.ttl --queries main/.github/workflow_resources/qc-queries/description-missing.sparql   
           java -jar robot.jar verify --input main/pmd-core-reasoned.ttl --queries main/.github/workflow_resources/qc-queries/https-missing.sparql

