name: reasoning validation

on:
  push:
    branches:
    - develop-3.0.0
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: develop-3.0.0
        path: main
    - name: Validate pmd-core.ttl by reasoning with ELK
      run: |
          curl -L -o robot.jar "https://github.com/ontodev/robot/releases/latest/download/robot.jar"
          java -jar robot.jar reason --catalog catalog-v001.xml --reasoner elk --input main/pmd-core.ttl --output main/pmd-core-reasoned.ttl

